{% set name = "gnu-units" %}
{% set version = "2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/units/units-{{ version }}.tar.gz
  sha256: d957b451245925c9e614c4513397449630eaf92bd62b8495ba09bbe351a17370

build:
  number: 0
  skip: true  # [win]
  script:
    - ./configure --prefix={{ PREFIX }}
    - make
    - make check
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - units m feet

about:
  home: https://www.gnu.org/software/units/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: GNU Units converts quantities expressed in various systems of measurement to their equivalents in other systems of measurement

extra:
  recipe-maintainers:
    - ngam
